name: docker build / push / deploy
on:
  push:
    branches:
    - main

env:
  PROJECT_ID: pokedevops
  APP_NAME: pokemon
  REGION: europe-west9
  REGISTRY: student-kevin
  CLOUDRUN_SERVICE_DEV: service-student-kevin-dev

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: export short sha env
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: export registry domain
        run: echo "REGISTRY_DOMAIN=${REGION}-docker.pkg.dev" >> $GITHUB_ENV

      - name: export image name env
        run: echo "IMAGE_NAME=${REGISTRY_DOMAIN}/${PROJECT_ID}/${REGISTRY}/${APP_NAME}:${GITHUB_SHA_SHORT}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: "gcloud auth"
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: gcloud configure docker 
        run: gcloud --quiet auth configure-docker ${REGION}-docker.pkg.dev

      - name: docker build 
        run: docker build --tag=${IMAGE_NAME} .
      
      - name: docker push 
        run: docker push ${IMAGE_NAME}

      - name: gcloud run deploy
        run: |
          gcloud run deploy ${CLOUDRUN_SERVICE_DEV} \
          --image=${IMAGE_NAME} \
          --project=${PROJECT_ID} \
          --region=${REGION} \
          --set-env-vars=VERSION=${GITHUB_SHA_SHORT}
