name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: pokedevops

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth activate-service-account --key-file ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

    - name: Build the Docker image
      run: docker build -t europe-west9-docker.pkg.dev/pokedevops/student-kevin/pokemon .

    - name: Push the Docker image
      run: docker push europe-west9-docker.pkg.dev/pokedevops/student-kevin/pokemon

    - name: Deploy to Cloud Run
      run: gcloud run deploy --image=europe-west9-docker.pkg.dev/pokedevops/student-kevin/pokemon service-student-kevin-dev
