name: Build, Push & Deploy Docker Image to Google Cloud

on:
  push:
    branches:
      - main

jobs:    
  build-and-push-preprod:
    runs-on: ubuntu-latest
    steps:
    
      - name: Pull commit_id
        run: |
          
        env:
          GCP_PROJECT: pokedevops
          GCP_REGION: europe-west

      - name: Docker tag
        run: |
          
        env:
          GCP_PROJECT: pokedevops
          GCP_REGION: europe-west

      - name: Docker push
        run: |
          
        env:
          GCP_PROJECT: pokedevops
          GCP_REGION: europe-west

          
      - name: Deploy to Google Cloud Run PREPROD
        run: |
          gcloud run deploy service-student-kevin-preprod --image=europe-west9-docker.pkg.dev/pokedevops/student-kevin/pokemon --project pokedevops --region europe-west9 --allow-unauthenticated
        env:
          GCP_PROJECT: pokedevops
          GCP_REGION: europe-west9
